### PR TITLE
Add SPM support

### LINKED ISSUE #6: Swiftpm support
We should add swift package manager support.

### PR DESCRIPTION
**Pull request by nidegen**
Resolves #6 

I tested it quickly, seems to work fine for me:)

### CODE REVIEW

**Comment by nidegen** [comment]
and, @proxpero ?

**Comment by ehlersd** [comment]
@proxpero I would also love to see this PR accepted and merged.

**Comment by nidegen** [comment]
@proxpero are your still there? :D

**Comment by nidegen** [comment]
@proxpero hello there?:D

**Pull request closed without merging**
